apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: iex-cluster
  region: eu-central-1
  version: "1.21"

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      allow: false



